version: '3'

vars:
  CONDAENV: reimbursement

tasks:
  dev-setup:
    desc: Setup the development environment
    summary: |
      Prepare your local development environment.

      It will:
      - Install the python with conda for the project;
      - Create a conda virtualenv with python based system development dependencies;
      - Install git pre-commit hooks;
    cmds:
      - task: pyenv:install
      - task: conda:create-env
      - task: pre-commit:install-hooks

  pyenv:install:
    cmds:
      - pyenv install --skip-existing

  conda:create-env:
    cmds:
      - conda env create -f environment.yaml
    status:
      - conda env list | grep {{.CONDAENV}}

  pre-commit:install-hooks:
    cmds:
      - pre-commit install

  install:
    cmds:
      - poetry install --no-interaction

  test:
    cmds:
      - nox --session tests --reuse-existing-virtualenvs

  reimbursement:version:
    cmds:
      - poetry run reimbursement-manager --version
