version: '3'

tasks:
  dev-setup:
    desc: Setup the development environment
    summary: |
      Prepare your local development environment.

      It will:
      - Install project's python version;
      - Install git pre-commit hooks;
      - Create Python virtual environment
    cmds:
      - task: pre-commit:install-hooks
      - task: python:create-venv

  pyenv:install:
    cmds:
      - pyenv install --skip-existing
    preconditions:
      - sh: command -v pyenv >/dev/null 2>&1
        msg: "Command `pyenv` not found. Halting"

  pre-commit:install-hooks:
    cmds:
      - pre-commit install
    preconditions:
      - sh: command -v pre-commit >/dev/null 2>&1
        msg: "Command pre-commit not found. Halting"

  python:create-venv:
    deps: ['pyenv:install']
    cmds:
      - python3 -m venv .venv

  install:
    cmds:
      - poetry install --no-interaction

  test:
    cmds:
      - nox --session tests --reuse-existing-virtualenvs
