version: '3'

tasks:
  dev-setup:
    desc: Setup the development environment
    cmds:
      - task: pre-commit:install-hooks

  pyenv:install:
    cmds:
      - pyenv install --skip-existing

  pre-commit:install-hooks:
    cmds:
      - pre-commit install
